// ─────────────────────────────────────────────────────────────────
// STONELINK PIPELINE — Leads réels (CSV dental + travel, Algérie)
// ─────────────────────────────────────────────────────────────────
import type { Prospect, Prototype } from '@/types/pipeline'

function makeDate(daysAgo: number): Date {
  const d = new Date()
  d.setDate(d.getDate() - daysAgo)
  return d
}

function id(n: number): string {
  return `01DZ${String(n).padStart(4, '0')}`
}

export const MOCK_PROSPECTS: Prospect[] = [
  // ── DENTAL LEADS ───────────────────────────────────────────────
  {
    id: id(1),
    companyName: 'Dentiste Dr SID épse Hammoudi',
    contactName: 'Dr. Hammoudi',
    email: '',
    phone: '0771 33 32 49',
    website: '',
    city: 'Alger',
    country: 'DZ',
    niche: 'dental',
    stage: 'to_call',
    priority: 'hot',
    lighthouseScore: 12,
    estimatedDealValue: 3500,
    estimatedLoss: 2100,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(1)}`, timestamp: makeDate(1), type: 'prospect_created', description: 'Import CSV dental Alger' }],
    agentHistory: [],
    createdAt: makeDate(1),
  },
  {
    id: id(2),
    companyName: 'Cabinet Dentaire Dr Boukir',
    contactName: 'Dr. Boukir',
    email: '',
    phone: '0541 02 76 14',
    website: '',
    city: 'Alger',
    country: 'DZ',
    niche: 'dental',
    stage: 'to_call',
    priority: 'hot',
    lighthouseScore: 8,
    estimatedDealValue: 4200,
    estimatedLoss: 2500,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(2)}`, timestamp: makeDate(1), type: 'prospect_created', description: 'Import CSV dental Alger' }],
    agentHistory: [],
    createdAt: makeDate(1),
  },
  {
    id: id(3),
    companyName: 'Nabet Dental Clinic',
    contactName: 'Dr. Nabet',
    email: '',
    phone: '0791 75 74 96',
    website: '',
    city: 'Alger',
    country: 'DZ',
    niche: 'dental',
    stage: 'new',
    priority: 'hot',
    lighthouseScore: 15,
    estimatedDealValue: 3800,
    estimatedLoss: 2200,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(3)}`, timestamp: makeDate(2), type: 'prospect_created', description: 'Import CSV dental Alger' }],
    agentHistory: [],
    createdAt: makeDate(2),
  },
  {
    id: id(4),
    companyName: 'Mahdi Dental Clinic',
    contactName: 'Dr. Mahdi',
    email: '28mahdi6meriem@gmail.com',
    phone: '0549 08 86 28',
    website: 'https://www.facebook.com/people/Mahdi-dental-clinic/100065040698832/',
    city: 'Alger',
    country: 'DZ',
    niche: 'dental',
    stage: 'interested',
    priority: 'hot',
    lighthouseScore: 32,
    estimatedDealValue: 4500,
    estimatedLoss: 2700,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(4)}`, timestamp: makeDate(2), type: 'prospect_created', description: 'Import CSV dental Alger' }],
    agentHistory: [],
    createdAt: makeDate(2),
  },
  {
    id: id(5),
    companyName: 'Razes Dental Clinic',
    contactName: 'Dr. Razes',
    email: '',
    phone: '0770 43 33 64',
    website: 'https://razes-dental.clinic/',
    city: 'Bab Ezzouar',
    country: 'DZ',
    niche: 'dental',
    stage: 'new',
    priority: 'warm',
    lighthouseScore: 41,
    estimatedDealValue: 3200,
    estimatedLoss: 1900,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(5)}`, timestamp: makeDate(3), type: 'prospect_created', description: 'Import CSV dental Alger' }],
    agentHistory: [],
    createdAt: makeDate(3),
  },
  {
    id: id(6),
    companyName: 'Super Smiles Dental Clinic',
    contactName: 'Dr. Smile',
    email: '',
    phone: '0550 03 00 66',
    website: 'https://supersmiles.dentalclinic/',
    city: 'Alger',
    country: 'DZ',
    niche: 'dental',
    stage: 'to_call',
    priority: 'warm',
    lighthouseScore: 38,
    estimatedDealValue: 4000,
    estimatedLoss: 2400,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(6)}`, timestamp: makeDate(3), type: 'prospect_created', description: 'Import CSV dental Alger' }],
    agentHistory: [],
    createdAt: makeDate(3),
  },
  {
    id: id(7),
    companyName: 'Clinique dentaire Neodental center',
    contactName: 'Dr. Neodental',
    email: '',
    phone: '0555 33 08 55',
    website: 'https://neogestion.pro/neodental/',
    city: 'Alger',
    country: 'DZ',
    niche: 'dental',
    stage: 'new',
    priority: 'warm',
    lighthouseScore: 52,
    estimatedDealValue: 4500,
    estimatedLoss: 2800,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(7)}`, timestamp: makeDate(4), type: 'prospect_created', description: 'Import CSV dental Alger' }],
    agentHistory: [],
    createdAt: makeDate(4),
  },
  {
    id: id(8),
    companyName: 'BS Dental Clinic',
    contactName: 'Dr. BS',
    email: '',
    phone: '0666 41 20 59',
    website: '',
    city: 'Alger',
    country: 'DZ',
    niche: 'dental',
    stage: 'new',
    priority: 'cold',
    lighthouseScore: 7,
    estimatedDealValue: 2800,
    estimatedLoss: 1500,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(8)}`, timestamp: makeDate(4), type: 'prospect_created', description: 'Import CSV dental Alger' }],
    agentHistory: [],
    createdAt: makeDate(4),
  },
  {
    id: id(9),
    companyName: 'Centre Dentaire Ain-Taya',
    contactName: 'Dr. Ain-Taya',
    email: 'Centredentaireat@gmail.com',
    phone: '',
    website: 'http://centredentaireaintaya.com/',
    city: 'Ain Taya',
    country: 'DZ',
    niche: 'dental',
    stage: 'interested',
    priority: 'hot',
    lighthouseScore: 49,
    estimatedDealValue: 5000,
    estimatedLoss: 3000,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(9)}`, timestamp: makeDate(5), type: 'prospect_created', description: 'Import CSV dental Alger' }],
    agentHistory: [],
    createdAt: makeDate(5),
  },
  {
    id: id(10),
    companyName: 'Norma dental clinic',
    contactName: 'Dr. Norma',
    email: '',
    phone: '0664 84 98 51',
    website: '',
    city: 'Alger',
    country: 'DZ',
    niche: 'dental',
    stage: 'new',
    priority: 'cold',
    lighthouseScore: 6,
    estimatedDealValue: 2500,
    estimatedLoss: 1400,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(10)}`, timestamp: makeDate(5), type: 'prospect_created', description: 'Import CSV dental Alger' }],
    agentHistory: [],
    createdAt: makeDate(5),
  },
  {
    id: id(11),
    companyName: 'Gr Dental Clinic',
    contactName: 'Dr. GR',
    email: 'mielucristian@gmail.com',
    phone: '0558 58 11 07',
    website: 'http://grdentalclinickouba.com/',
    city: 'Kouba',
    country: 'DZ',
    niche: 'dental',
    stage: 'to_call',
    priority: 'hot',
    lighthouseScore: 41,
    estimatedDealValue: 4200,
    estimatedLoss: 2600,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(11)}`, timestamp: makeDate(1), type: 'prospect_created', description: 'Import CSV dental Alger' }],
    agentHistory: [],
    createdAt: makeDate(1),
  },

  // ── TRAVEL LEADS ───────────────────────────────────────────────
  {
    id: id(51),
    companyName: 'CopyFly Algeria',
    contactName: 'Responsable CopyFly',
    email: 'reservation@copyflyalgeria.com',
    phone: '0552 63 02 94',
    website: 'http://copyflyalgeria.com/',
    city: 'Alger',
    country: 'DZ',
    niche: 'travel',
    stage: 'to_call',
    priority: 'hot',
    lighthouseScore: 31,
    estimatedDealValue: 3500,
    estimatedLoss: 2000,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(51)}`, timestamp: makeDate(1), type: 'prospect_created', description: 'Import CSV travel Alger' }],
    agentHistory: [],
    createdAt: makeDate(1),
  },
  {
    id: id(52),
    companyName: 'Mezine Travel Alger Plage',
    contactName: 'Responsable Mezine',
    email: '',
    phone: '0540 41 49 92',
    website: '',
    city: 'Alger Plage',
    country: 'DZ',
    niche: 'travel',
    stage: 'new',
    priority: 'warm',
    lighthouseScore: 12,
    estimatedDealValue: 2800,
    estimatedLoss: 1600,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(52)}`, timestamp: makeDate(2), type: 'prospect_created', description: 'Import CSV travel Alger' }],
    agentHistory: [],
    createdAt: makeDate(2),
  },
  {
    id: id(53),
    companyName: 'El Ihcene Tourisme',
    contactName: 'Responsable El Ihcene',
    email: 'elihcene.algerplage@gmail.com',
    phone: '0563 93 59 95',
    website: 'https://www.elihcene-voyage.com/',
    city: 'Alger',
    country: 'DZ',
    niche: 'travel',
    stage: 'to_call',
    priority: 'hot',
    lighthouseScore: 45,
    estimatedDealValue: 4000,
    estimatedLoss: 2400,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(53)}`, timestamp: makeDate(1), type: 'prospect_created', description: 'Import CSV travel Alger' }],
    agentHistory: [],
    createdAt: makeDate(1),
  },
  {
    id: id(54),
    companyName: 'Cygne bleu',
    contactName: 'Responsable Cygne',
    email: 'res-billet@cygnebleu.dz',
    phone: '0550 05 35 14',
    website: 'http://cygnebleu.dz/',
    city: 'Alger',
    country: 'DZ',
    niche: 'travel',
    stage: 'new',
    priority: 'warm',
    lighthouseScore: 38,
    estimatedDealValue: 3200,
    estimatedLoss: 1900,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(54)}`, timestamp: makeDate(3), type: 'prospect_created', description: 'Import CSV travel Alger' }],
    agentHistory: [],
    createdAt: makeDate(3),
  },
  {
    id: id(55),
    companyName: 'Numidia Travel Services',
    contactName: 'Responsable Numidia',
    email: '',
    phone: '0553 70 47 24',
    website: 'http://www.numidiatravel.com/',
    city: 'Alger',
    country: 'DZ',
    niche: 'travel',
    stage: 'to_call',
    priority: 'hot',
    lighthouseScore: 29,
    estimatedDealValue: 4500,
    estimatedLoss: 2700,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(55)}`, timestamp: makeDate(1), type: 'prospect_created', description: 'Import CSV travel Alger' }],
    agentHistory: [],
    createdAt: makeDate(1),
  },
  {
    id: id(56),
    companyName: 'HICHAM TOUR',
    contactName: 'Responsable Hicham',
    email: 'info@hichamtour.com',
    phone: '0770 16 01 77',
    website: 'https://hichamtour.com/',
    city: 'Alger',
    country: 'DZ',
    niche: 'travel',
    stage: 'new',
    priority: 'warm',
    lighthouseScore: 42,
    estimatedDealValue: 3800,
    estimatedLoss: 2200,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(56)}`, timestamp: makeDate(4), type: 'prospect_created', description: 'Import CSV travel Alger' }],
    agentHistory: [],
    createdAt: makeDate(4),
  },
  {
    id: id(57),
    companyName: 'Freedom travel algeria',
    contactName: 'Responsable Freedom',
    email: 'freedomtravelalgeria@gmail.com',
    phone: '0698 61 10 75',
    website: 'http://www.freedomtravelalgeria.com/',
    city: 'Alger',
    country: 'DZ',
    niche: 'travel',
    stage: 'interested',
    priority: 'hot',
    lighthouseScore: 51,
    estimatedDealValue: 4200,
    estimatedLoss: 2600,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(57)}`, timestamp: makeDate(5), type: 'prospect_created', description: 'Import CSV travel Alger' }],
    agentHistory: [],
    createdAt: makeDate(5),
  },
  {
    id: id(58),
    companyName: 'Riwaya Travel',
    contactName: 'Responsable Riwaya',
    email: 'contact@riwayatravel.com',
    phone: '+33 1 84 80 65 45',
    website: 'https://www.riwayatravel.com/',
    city: 'Alger',
    country: 'DZ',
    niche: 'travel',
    stage: 'new',
    priority: 'cold',
    lighthouseScore: 48,
    estimatedDealValue: 3500,
    estimatedLoss: 2000,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(58)}`, timestamp: makeDate(6), type: 'prospect_created', description: 'Import CSV travel Alger' }],
    agentHistory: [],
    createdAt: makeDate(6),
  },
  {
    id: id(59),
    companyName: 'Oryx Voyages',
    contactName: 'Responsable Oryx',
    email: 'contact@oryxvoyages.com',
    phone: '0699 84 39 39',
    website: 'http://www.oryxvoyage.com/',
    city: 'Alger',
    country: 'DZ',
    niche: 'travel',
    stage: 'to_call',
    priority: 'hot',
    lighthouseScore: 55,
    estimatedDealValue: 4800,
    estimatedLoss: 2900,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(59)}`, timestamp: makeDate(1), type: 'prospect_created', description: 'Import CSV travel Alger' }],
    agentHistory: [],
    createdAt: makeDate(1),
  },
  {
    id: id(60),
    companyName: 'El Kinana Voyages',
    contactName: 'Responsable El Kinana',
    email: 'elkinanavoyages@gmail.com',
    phone: '023 80 26 23',
    website: 'http://www.elkinanavoyages.com/',
    city: 'Alger',
    country: 'DZ',
    niche: 'travel',
    stage: 'new',
    priority: 'warm',
    lighthouseScore: 46,
    estimatedDealValue: 3000,
    estimatedLoss: 1800,
    notes: [],
    emails: [],
    activities: [{ id: `act-${id(60)}`, timestamp: makeDate(7), type: 'prospect_created', description: 'Import CSV travel Alger' }],
    agentHistory: [],
    createdAt: makeDate(7),
  },
]

export const MOCK_PROTOTYPES: Prototype[] = [
  {
    id: 'dental-zekri',
    niche: 'dental',
    name: 'Zekri Clinic',
    description: 'Design élégant pour cliniques dentaires algériennes. Moderne, épuré, booking intégré.',
    thumbnailUrl: '/prototypes/dental/zekri-built/assets/thumbnail.png',
    filePath: '/prototypes/dental/zekri-built/index.html',
    demoUrl: '/prototypes/dental/zekri-built/index.html',
    customizableFields: ['COMPANY_NAME', 'LOGO_SRC', 'PRIMARY_COLOR', 'PHONE', 'ADDRESS', 'TAGLINE', 'EMAIL'],
    tags: ['moderne', 'algérie', 'dental', 'booking'],
    recommendedFor: ['cabinet dentaire', 'clinique dentaire', 'implantologie'],
  },
  {
    id: 'travel-parfait',
    niche: 'travel',
    name: 'Parfait Voyage',
    description: 'Site vitrine premium pour agences de voyage. Design travel inspirant, destinations en avant.',
    thumbnailUrl: '/prototypes/travel/parfait-built/assets/thumbnail.png',
    filePath: '/prototypes/travel/parfait-built/index.html',
    demoUrl: '/prototypes/travel/parfait-built/index.html',
    customizableFields: ['COMPANY_NAME', 'LOGO_SRC', 'PRIMARY_COLOR', 'PHONE', 'ADDRESS', 'TAGLINE', 'EMAIL'],
    tags: ['voyage', 'luxe', 'algérie', 'destinations'],
    recommendedFor: ['agence de voyage', 'tourisme', 'tours opérateur'],
  },
]
