import type { PrototypeCatalogItem } from '@/components/modules/pipeline/prototype/PrototypeCard';

export const PROTOTYPE_CATALOG: PrototypeCatalogItem[] = [
  {
    id: 'proto_dental_elite',
    niche: 'dental',
    name: 'Clinique Dentaire Signature',
    description: 'Une vitrine moderne et haut de gamme conçue pour inspirer confiance et attirer des patients premium.',
    thumbnailUrl: '',
    recommendedFor: ['Cabinet Dentaire', 'Chirurgien Esthétique'],
    tags: ['Efficace', 'Luxueux', 'Conversion'],
    defaultValues: {
      PRIMARY_COLOR: '#0d2b45',
      HERO_TITLE: 'Votre Sourire, Notre Art et Expertise',
      HERO_SUBTITLE: 'Des soins dentaires d\'exception dans un cadre chaleureux et à la pointe de la technologie.',
      CTA_TEXT: 'Prendre Rendez-vous en Ligne',
      BENEFIT_1: 'Technologie 3D avancée',
      BENEFIT_2: 'Équipe d\'experts hautement qualifiés',
      BENEFIT_3: 'Confort absolu et sédation douce',
    },
    customizableFields: ['PRIMARY_COLOR', 'HERO_TITLE', 'HERO_SUBTITLE', 'CTA_TEXT', 'BENEFIT_1', 'BENEFIT_2', 'BENEFIT_3'],
  },
  {
    id: 'proto_travel_escape',
    niche: 'travel',
    name: 'Visions d\'Évasion Luxury',
    description: 'Une expérience visuelle immersive pensée pour les agences de voyages haut de gamme et resorts.',
    thumbnailUrl: '',
    recommendedFor: ['Hôtel de Luxe', 'Agence de Voyage', 'Château'],
    tags: ['Cinématique', 'Immersif', 'Rêve'],
    defaultValues: {
      PRIMARY_COLOR: '#8d704b',
      HERO_TITLE: 'Découvrez des Horizons Inexplorés',
      HERO_SUBTITLE: 'Des séjours sur-mesure d\'un raffinement absolu à travers les plus belles destinations du monde.',
      CTA_TEXT: 'Créer Mon Itinéraire',
      BENEFIT_1: 'Sélection d\'hôtels 5 étoiles certifiés',
      BENEFIT_2: 'Conciergerie privée accessible 24/7',
      BENEFIT_3: 'Expériences locales exclusives',
    },
    customizableFields: ['PRIMARY_COLOR', 'HERO_TITLE', 'HERO_SUBTITLE', 'CTA_TEXT', 'BENEFIT_1', 'BENEFIT_2', 'BENEFIT_3'],
  },
  {
    id: 'proto_realestate_castle',
    niche: 'realestate',
    name: 'Domaines & Demeures Privées',
    description: 'Une plateforme d\'exception pour valoriser des portefeuilles immobiliers de prestige et capter des mandats exclusifs.',
    thumbnailUrl: '',
    recommendedFor: ['Courtier Prestige', 'Agence Immobilière'],
    tags: ['Épuré', 'Majestueux', 'Rendement'],
    defaultValues: {
      PRIMARY_COLOR: '#1a2b24',
      HERO_TITLE: 'L\'Immobilier de Prestige Reconfiguré',
      HERO_SUBTITLE: 'Accédez à des propriétés d\'exception hors marché et vendez en toute confidentialité.',
      CTA_TEXT: 'Estimer Mon Bien',
      BENEFIT_1: 'Réseau d\'acquéreurs internationaux qualifiés',
      BENEFIT_2: 'Valorisation par drone et visite 3D immersive',
      BENEFIT_3: 'Accompagnement fiscal et juridique complet',
    },
    customizableFields: ['PRIMARY_COLOR', 'HERO_TITLE', 'HERO_SUBTITLE', 'CTA_TEXT', 'BENEFIT_1', 'BENEFIT_2', 'BENEFIT_3'],
  },
  {
    id: 'proto_saas_hyper',
    niche: 'saas',
    name: 'HyperDrive OS UI',
    description: 'Landing page ultra-rapide optimisée pour la conversion de produits technologiques et logiciels de pointe.',
    thumbnailUrl: '',
    recommendedFor: ['Logiciel', 'Startup', 'Fintech'],
    tags: ['Vitesse', 'Futuriste', 'Technologique'],
    defaultValues: {
      PRIMARY_COLOR: '#3b82f6',
      HERO_TITLE: 'Accélérez Votre Workflow de 200%',
      HERO_SUBTITLE: 'La plateforme unifiée pour centraliser vos données, automatiser vos relances et piloter votre croissance.',
      CTA_TEXT: 'Commencer l\'Essai Gratuit',
      BENEFIT_1: 'Intégration API en un seul clic',
      BENEFIT_2: 'Sécurité bancaire de bout en bout',
      BENEFIT_3: 'Rapports d\'analyse propulsés par l\'IA',
    },
    customizableFields: ['PRIMARY_COLOR', 'HERO_TITLE', 'HERO_SUBTITLE', 'CTA_TEXT', 'BENEFIT_1', 'BENEFIT_2', 'BENEFIT_3'],
  }
];
